dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
services:
  - postgresql
script: bundle exec rake test
before_install:
  - createdb pgslice_test
notifications:
  email:
    on_success: never
    on_failure: change
matrix:
  include:
    - name: "Postgres 9.6"
      addons:
        postgresql: "9.6"
    - name: "Postgres 10"
      addons:
        postgresql: "10"
    - name: "Postgres 11"
      addons:
        postgresql: "11"
        apt:
          packages:
            - postgresql-11
      env:
        - PGPORT=5433
        - PGSLICE_URL=postgres://:5433/pgslice_test
    - name: "Postgres 12"
      addons:
        postgresql: "12"
        apt:
          sources:
            - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main 12
              key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
          packages:
            - postgresql-12
      env:
        - PGPORT=5433
        - PGSLICE_URL=postgres://:5433/pgslice_test
